### ISSUE TITLE
BugFix: npm build시 발생하는 오류 해결안

### ISSUE THREAD

**Issue by xxbeann** [ais-internship-cnu/I-school-FE#26]
## npm build시 발생하는 오류 해결안

> npm build시 오류가 발생합니다. 이를 해결해야 나중에 npm start를 할 수 있습니다.

## 작업 상세 내용

- [x] 오류 해결하기

**Comment by dnjfqhd12345** [comment]
오류 해결 완료
참조 PR:  #37
